### PR TITLE
feat(ui): added german translations

### LINKED ISSUE #468: Help Us Translate
TODO 🚧

### PR DESCRIPTION
**Pull request by Paradiesvogel7**
## What type of PR is this?

/kind feature

## What this PR does / why we need it:

It adds german translations to the ui. as discussed in #468 

I've tried to make the translations as accurate as possible. if something doesn't fit, please let me know.

## Which issue(s) this PR fixes:

Fixes #468 (a part of it)

### CODE REVIEW

**Comment by Paradiesvogel7** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by elliotxx — APPROVED** [review]
Good Job! LGTM

**Comment by Paradiesvogel7** [comment]
> LGTM

thx

**Comment by elliotxx** [comment]
I suddenly realized that the value of placeholder in the search bar was not added to the i18n file. I will create a separate PR later to fix it together. @Paradiesvogel7 

image

**Pull request merged**
