### PR TITLE
feat(lang): translated UI to Portuguese

### PR DESCRIPTION
**Pull request by virtually-stray**
## What type of PR is this?

/kind feature

## What this PR does / why we need it:

Translated the APP UI to Portuguese
as discussed in [#468](https://github.com/KusionStack/karpor/issues/468)

Related issues [#468](https://github.com/KusionStack/karpor/issues/468)

### CODE REVIEW

**Comment by elliotxx** [comment]
After I started locally, it didn't seem to take effect:

image

**Comment by virtually-stray** [comment]
Sorry, I forgot  to add a file to the commit. I fixed it and tested it on my machine. It should be working now.



> @virtually-stray After I started locally, it didn't seem to take effect:
> 
> image

**Comment by virtually-stray** [comment]
image

**Review by elliotxx — APPROVED** [review]
Good Job! LGTM

**Pull request merged**
