### PR TITLE
feat: show VersionNumber in dashboard

### PR DESCRIPTION
**Pull request by solarhell**
Ref: https://github.com/KusionStack/karpor/issues/362

Preview:

image

### CODE REVIEW

**Comment by solarhell** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by elliotxx** [comment]
@solarhell Hello, I found that the `License Check` failed because the VERSION file was checked incorrectly. Can you add `pkg/version/VERSION` to the `paths-ignore` in `.licenserc.yaml`?

image

image

**Comment by solarhell** [comment]
@elliotxx Added, please check.

**Review by elliotxx — APPROVED** [review]
lgtm

**Pull request merged**
