### PR TITLE
feat(ui): control whether the Github logo is displayed

### LINKED ISSUE #501: Experience: Whether the GitHub Badge is displayed through the flag in /server-configs
### What would you like to be added?

Whether the GitHub logo is displayed through the flag in /server-configs.

GitHub logo is used to jump to Karpor's github repo. Sometimes, users do not need this link. For example, when deploying within the company.

image

You can call the `$HOST/server-configs` in the front-end code to get the server configurations, including whether to display the github logo, which is set by the service deployer.

image

### Why is this needed?

Sometimes, users do not need this github logo. For example, when deploying within the company.

### PR DESCRIPTION
**Pull request by z1cheng**
## What type of PR is this?
/kind feature

## What this PR does / why we need it:

Control whether the Github logo is displayed in UI

## Which issue(s) this PR fixes:

Close #501

### CODE REVIEW

**Comment by z1cheng** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by elliotxx** [comment]
@z1cheng Cool, let us review it. cc @hai-tian

**Comment by z1cheng** [comment]
@elliotxx Do we have any instructions/Makefile to run karpor locally for better testing and debugging the code? including creating a cluster(Kind?), building images, installing with helm?

**Comment by elliotxx** [comment]
@z1cheng  Of course, you can execute `make help` in the project root directory to view all targets, as well as view documents [Code Contribute](https://www.kusionstack.io/karpor/developer-guide/contribution-guide/code-contribute#running-karpor-locally) to view how to start locally. If you need, I will provide more details on local startup and debugging.

**Review by elliotxx — APPROVED** [review]
lgtm

**Comment by elliotxx** [comment]
@z1cheng Hi, I have released version [0.4.6](https://github.com/KusionStack/karpor/releases/tag/v0.4.6) with this feature included.

**Pull request merged**
